Add new parsed prop: build context
Runnable/octobear pull request #14
Opened 2017-04-12 00:29 UTC by podviaznikov

2017-04-12 23:14 UTC, podviaznikov commented
<img width="865" alt="1__podviaznikov_anton-macpro____runnable_octobear__zsh_" src="https://cloud.githubusercontent.com/assets/429706/24983319/215e2f58-1f9b-11e7-8905-9e4699bb3cbc.png">

2017-04-12 23:17 UTC, thejsj approved these changes

2017-04-15 00:48 UTC, podviaznikov commented
![5__podviaznikov_anton-macpro____runnable_octobear__zsh_](https://cloud.githubusercontent.com/assets/429706/25059375/9ddfbcb8-213a-11e7-9fef-e6179a3231d8.png)

2017-04-17 20:54 UTC, Nathan219 commented on lib/parser.js
> +   * @return {Object|Null}    object with  `dockerFilePath` and `dockerBuildContext` props
Looks like it'll never return a null anymore

2017-04-17 21:05 UTC, Nathan219 requested changes

2017-04-17 21:05 UTC, Nathan219 commented on lib/parser.js
> +    const dockerFilePath = Parser.isScmUrl(scmDomain, dockerContextPath)
make if, since both ternaries use the same check

2017-04-17 22:09 UTC, podviaznikov commented on lib/parser.js
> +   * @return {Object|Null}    object with  `dockerFilePath` and `dockerBuildContext` props
see here https://github.com/Runnable/octobear/blob/2cce0b365a9517c6efa1c28f53b517d923dedcc8/lib/parser.js#L68

2017-04-17 22:09 UTC, podviaznikov commented on lib/parser.js
> +   * @return {Object|Null}    object with  `dockerFilePath` and `dockerBuildContext` props
see here https://github.com/Runnable/octobear/blob/2cce0b365a9517c6efa1c28f53b517d923dedcc8/lib/parser.js#L68

2017-04-17 22:32 UTC, Nathan219 commented on lib/parser.js
> +        dockerBuildContext: undefined
lol, why not just not add it?

2017-04-17 22:38 UTC, podviaznikov commented on lib/parser.js
> +        dockerBuildContext: undefined
because we don't need it. It not actually build context. It's a remove url

2017-04-17 22:44 UTC, Nathan219 approved these changes

2017-04-17 22:56 UTC, podviaznikov commented
<img width="929" alt="1__podviaznikov_anton-macpro____runnable_octobear__zsh_" src="https://cloud.githubusercontent.com/assets/429706/25107799/6e661c36-2386-11e7-825a-cbf0179efd54.png">

2017-04-17 22:56 UTC, merged